databases:
  - name: comercium-db
    plan: free

services:
  - type: web
    name: comercium-web
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers ${WEB_CONCURRENCY:-2}
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: comercium-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"
      # Variables de tu app (completa estos valores en el dashboard o aqu√≠ si prefieres)
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ACCOUNT_EMAIL_VERIFICATION
        value: "mandatory"
